// Generated by https://quicktype.io

export interface DocumentosAgendaType {
    id:                          null;
    clienteId:                   null;
    concorrenteId:               null;
    clienteNome:                 null;
    concorrenteNome:             null;
    tipoDocumentoId:             number;
    tipoDocumento:               string;
    arquivo:                     null;
    tipoArquivo:                 null;
    descricao:                   null;
    dataCadastro:                null;
    colaboradorId:               null;
    dataValidade:                null;
    vencido:                     null;
    charter:                     null;
    tamanhoDocumento:            null;
    oportunidadeTipoDocumentoId: null;
}
