// Generated by https://quicktype.io

export interface GraphParticipaciones {
    id:          number;
    fantasia:    string;
    vencidas:    number;
    perdidas:    number;
    suspensas:   number;
    fracassadas: number;
    andamento:   number;
    canceladas:  number;
    desertas:    number;
}
