// Generated by https://quicktype.io

export interface ListAllTaskByOpportunityId {
    dataTarefaFimPlanejada: string;
    dataTarefaFimRealizada: string;
    descricaoTarefa:        string;
    responsavel:            string;
    status:                 string;
}
