// Generated by https://quicktype.io

export interface ListJudgeResourceByOpportunityId {
    clausulaRecurso: string;
    dataProtocolo:   string;
    demandaId:       number;
    oportunidadeId:  number;
    procedimento:    string;
    resultado:       string;
}
