// Generated by https://quicktype.io

export interface ListAllRequirementByOpportunityAux {
    id:number,
    descripcion:string,
    tipo:string,
    tipoUsuario:string,
    dias:string,
    acepto:string
}
