// Generated by https://quicktype.io

export interface ListAllRequirementByOpportunity {
    atende:     string;
    descricao:  string;
    metaDias:   string;
    observacao: string;
    tipoMeta:   string;
    usuario:    string;
}
