// Generated by https://quicktype.io

export interface ListaParecer {
    oportunidadeId:number;
    nomeOrgao:string;
    linkEdital:null;
    numeroEdital:string;
    descricao:string;
    dataCertame:string;
    horaCertame:string;
    descricaoModalidade:string;
    localidade:string;
    estado:string;
    contratoId:number;
    clienteId:number;
    nomeCliente:string;
    meEpp:string;
    parecerId:number;
    dataProposta:string;
    registroPreco:string;
    colaboradorId:number;
    arquivo:string;
    tipoArquivo:null;
    linkTermoReferencia:null;
    prazoEntrega:null;
    prazoPagamento:null;
    enderecoEntrega:null;
    enderecoEnvioDocumentacao: null;
    usuarioId:string;
    dataImpugnacao:string;
    dataEsclarecimento:string;
    exibeExigencia:string;
    realizado:string;
}
