// Generated by https://quicktype.io

export interface ListaParecerAux {
    id:number,
    opinion:string,
    idOpinion:string,
    edital:string,
    oragao:string,
    fechaOpinion:string,
    ubicacion:string,
    estatus:number,
    clienteId:number,
    modalidade:string,
    plataforma:string
}
