// Generated by https://quicktype.io

export interface NotificacionByLoginAux {
    id:          string;
    tipo:        string;
    dia:         string;
    hora:        string;
    descripcion: string;
    color:       string;
    background:  string;
    icon:        string;
    diaVisible:  boolean;
}
