// Generated by https://quicktype.io

export interface NotificationListByLogin {
    charter:         number;
    dataAtualizacao: string;
    dataCadastro:    string;
    id:              number;
    importante:      string;
    login:           string;
    mensagem:        string;
    status:          string;
    tipoMensagem:    TipoMensagem;
}

export interface TipoMensagem {
    descricao: string;
    id:        number;
}
