// Generated by https://quicktype.io

export interface OpportunityCustomListOpinionsById {
    parecerId:        number;
    parecerUsuarioId: number;
    colaboradorId?:   number;
    nomeColaborador?: string;
    parecer:          string;
    justificativa:    string;
    dataParecer:      number;
    usuarioId?:       number;
    nomeUsuario?:     string;
}
