// Generated by https://quicktype.io

export interface OpportunityCustomFindById {
    descricaoOportunidade:    string;
    dataCertame:              string;
    dataCertameInicial:       string;
    horaCertame:              string;
    horaCertameInicial:       string;
    statusOportunidade:       string;
    descricaoModalidade:      string;
    edital:                   string;
    razaoSocialCliente:       string;
    cnpjCliente:              string;
    localidade:               string;
    arquivo:                  string;
    tipoArquivo:              string;
    razaoSocialOrgao:         string;
    cnpjOrgao:                string;
    razaoSocialOrgaoCondutor: string;
    cnpjOrgaoCondutor:        string;
    orgaoContrato:            string;
    pendencia:                string;
    oportunidadeGanha:        string;
    meEpp:                    string;
    valorFaturado:            number;
    saldoOportunidade:        number;
    statusFaturamento:        string;
    registroPreco:            string;
    dataProposta:             number;
    plataforma:               string;
    dataImpugnacao:           number;
    dataEsclarecimento:       number;
    dataCadastro:             number;
    modalidade:               string;
    dataCaptacao:             string;
    pregoeiroTelefone:        string;
    compulsorio:              string;
}
