// Generated by https://quicktype.io

                 
export interface OpportunityCustomListOpinionsByIdAux {
        id:number,
        responsable:string,
        tipo:string,
        parecer:string,
        fecha:string
}
