// Generated by https://quicktype.io

export interface ParecerSearch {
    dataParecer:            number;
    descricaoMotivoParecer: string;
    justificativa:          string;
    motivoParecerId:        number;
    nomeUsuario:            string;
    parecer:                string;
    parecerId:              number;
    parecerUsuarioId:       number;
    usuarioId:              number;
}
