import React from 'react'

// export interface AgendaItem {
//     dots:              Dot[];
//     selected:          boolean;
//     selectedColor:     string;
//     selectedTextColor: string;
// }

// export interface Dot {
//     key:              string;
//     color:            string;
//     selectedDotColor: string;
// }
// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface AgendaItem {
    dataCertame:        Date;
    horaCertame:        string;
    oportunidadeId:     number;
    cliente:            string;
    orgao:              string;
    plataforma:         string;
    registroPreco:      string;
    status:             string;
    statusJuridico:     string;
    statusEstrategico:  string;
    parecerEstrategico: null | string;
}

