// Generated by https://quicktype.io

export interface ErrorResponse {
    message: string;
    name:    string;
    stack:   string;
    config:  Config;
    code:    string;
    status:  null;
}

export interface Config {
    transitional:      Transitional;
    transformRequest:  null[];
    transformResponse: null[];
    timeout:           number;
    xsrfCookieName:    string;
    xsrfHeaderName:    string;
    maxContentLength:  number;
    maxBodyLength:     number;
    headers:           Headers;
    baseURL:           string;
    auth:              Auth;
    method:            string;
    url:               string;
    data:              string;
}

export interface Auth {
    username: string;
    password: string;
}

export interface Headers {
    Accept:         string;
    "Content-Type": string;
    Authorization:  string;
}

export interface Transitional {
    silentJSONParsing:   boolean;
    forcedJSONParsing:   boolean;
    clarifyTimeoutError: boolean;
}
