// Generated by https://quicktype.io

export interface Exigencias {
    id:                   number;
    metaDias:             string;
    observacao:           string;
    oportunidadeId:       number;
    status:               string;
    tipoDataMeta:         number;
    tipoExigenciaId:      number;
    tipoUsuarioClienteId: number;
    titulo:               string;
}
