// Generated by https://quicktype.io

export interface OpinionesRequest {
    motivoParecerId:               string;
    justificativa:                 string;
    parecer:                       string;
    valores:                       OportunidadesProdutosServico[];
    importExportInput:             null;
    exibeAbaValor:                 string;
    collaboratorUser:              null;
    oportunidadeExigencia:         any[];
    usuarioId:                     number;
    parecerId:                     number;
    oportunidadesProdutosServicos: OportunidadesProdutosServico[];
    lote:                          any[];
    oportunidadeId:                number;
    charter:                       number;
}

export interface OportunidadesProdutosServico {
    id:              number;
    motivoParecerId: null;
    familiaId:       number;
    produtoId:       number;
    observacao:      string;
    valorInicial:    number;
    valorFinal:      number;
    parecerItem:     null;
    kitId:           null;
}
