// Generated by https://quicktype.io

export interface ParecerRealizado {
    parecerId:        number;
    parecerUsuarioId: number;
    colaboradorId:    number;
    nomeColaborador:  string;
    parecer:          string;
    justificativa:    string;
    clausulas:        any[];
}
