// Generated by https://quicktype.io

export interface TipoUsuario {
    id:        number;
    descricao: string;
    status:    string;
    charter:   number;
}

// export enum Descricao {
//     Estratégico = "ESTRATÉGICO",
//     Financeiro = "FINANCEIRO",
//     Operação = "OPERAÇÃO",
//     Rede = "REDE",
// }

// export enum Status {
//     A = "A",
// }
